name: bloc
description: >
  A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 8.0.0-develop
repository: https://github.com/PlugFox/bloc/tree/master/packages/bloc
issue_tracker: https://github.com/PlugFox/bloc/issues
homepage: https://github.com/PlugFox/bloc
#documentation: https://bloclibrary.dev

publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.1.0
  pedantic: ^1.10.0
  rxdart: ^0.26.0
  test: ^1.16.0
